app = 'publiclogic-puddlejumper-staging'
primary_region = 'ewr'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    type = "http"
    interval = "15s"
    timeout = "3s"
    grace_period = "10s"
    method = "get"
    path = "/health"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[mounts]]
  source = 'data_staging'
  destination = '/app/data'
  initial_size = '1gb'

[env]
  CONTROLLED_DATA_DIR = '/app/data'
  PORT = '3002'
